version: "3"
services:
  redis:
    container_name: redis-ec2
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - ./data/:/data
  app:
    build:
        context: .
        dockerfile: Dockerfile
    container_name: spring-boot
    ports:
      - 8080:8080